### ISSUE TITLE
Segundo test

### ISSUE THREAD

**Issue by CintiaCastilloCareglio** [CintiaCastilloCareglio/practica_dwec_gestor_presupuesto#1]
Buenas @pedroprieto. No consigo pasar el segundo test y no sé muy bien porqué. ¿Le puedes echar un ojo a mis commits o tengo que hacer la pull request para que veas el ejercicio? Gracias de antemano.

**Comment by pedroprieto** [comment]
Buenas,

Puedo verlo, tranquila. Varias cosas:
- Esta comparación debería ser al revés: si no se encuentran (`pos == -1`), se añaden:
  https://github.com/CintiaCastilloCareglio/practica_dwec_gestor_presupuesto/blob/fb9f1e43936f2b980aca770778bc5ecd98e95bef/js/gestionPresupuesto.js#L61
- Aquí igual: si se encuentran, se quitan:
  https://github.com/CintiaCastilloCareglio/practica_dwec_gestor_presupuesto/blob/fb9f1e43936f2b980aca770778bc5ecd98e95bef/js/gestionPresupuesto.js#L76
- Aquí te sobran los espacios al inicio y los retornos de carro al final: las plantillas ya los introducen al poner el texto en nueva línea.
  https://github.com/CintiaCastilloCareglio/practica_dwec_gestor_presupuesto/blob/fb9f1e43936f2b980aca770778bc5ecd98e95bef/js/gestionPresupuesto.js#L88-L90
  ```js
        txt += `Gasto correspondiente a ${this.descripcion} con valor ${valor} €
  Fecha: ${fechaLocal}
  Etiquetas:\n`; 
  ```

Un saludo!

**Comment by CintiaCastilloCareglio** [comment]
Muchas gracias @pedroprieto !! No lo veía.
