### ISSUE TITLE
Fallo

### ISSUE THREAD

**Issue by pedroprieto** [CintiaCastilloCareglio/practica_dwec_gestor_presupuesto#2]
Hola, @CintiaCastilloCareglio 

El fallo está aquí, te falta la extensión `.js`:
https://github.com/CintiaCastilloCareglio/practica_dwec_gestor_presupuesto/blob/afa18473b43e4110c4789c0115f75b4a3c2a52e9/js/generarDatosEstaticos.js#L2-L3

Un saludo!

**Comment by CintiaCastilloCareglio** [comment]
Hola @pedroprieto muchísimas gracias!! Me di cuenta esta mañana de que no había hecho el issue donde tocaba al no encontrarlo 😅​
Ahora que he añadido bien el nombre de los archivos a importar, el html se me ve perfecto y ya paso todos los tests. 
Gracias! Gracias!
