### ISSUE TITLE
Función nuevogastoFormulario y anyadirFormulario

### ISSUE THREAD

**Issue by CintiaCastilloCareglio** [CintiaCastilloCareglio/practica_dwec_gestor_presupuesto#3]
Buenas @pedroprieto !
Cuando añado un gasto formulario, en vez de sumarse su valor a gastos totales, me lo añade al final, como si hubiera añadido decimales. No veo porqué.
Gracias de antemano

**Comment by pedroprieto** [comment]
¿Es posible que se te haya olvidado convertir a número el dato que lees del campo del formulario? Como hiciste aquí:
https://github.com/CintiaCastilloCareglio/practica_dwec_gestor_presupuesto/blob/f5bb1c75183196e5a960f295b61a5775038f8d4a/js/gestionPresupuestoWeb.js#L272

Un saludo!

**Comment by CintiaCastilloCareglio** [comment]
Por supuesto que era eso!! Gracias
Te hago la PR ya mismo @pedroprieto 😊​
